### ISSUE TITLE
Speed up gradle check by caching publishToMavenLocal

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk#53]
Gradle checks on PRs are taking a very long time.  A check of [recent GitHub Actions](https://github.com/opensearch-project/opensearch-sdk/actions) shows 8 to 9 minutes to execute the check.

The longest amount of time spent in the build is publishToMavenLocal:
https://github.com/opensearch-project/opensearch-sdk/blob/2ca7fb186203d34b708123fbf5ebf64ba612fea6/.github/workflows/build.yml#L12-L14

We should investigate using the cache action to save the maven local state across runs, and speed up later builds:
https://github.com/actions/cache

Assuming the publishing just goes to the repository under `.m2` the syntax would be:
```yaml
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/some-file-here') }}
          restore-keys: ${{ runner.os }}-m2
```
where "some-file-here" would be a local file that would change when the feature/extensions branch was updated and needed to be re-published.  I'd suggest storing the hash of the latest feature/extensions commit in such a file.
